export const data = [
  {
    name: "Наладчик станков с ЧПУ ",
    payments: "два раза в месяц",
    experience: "1–3 года",
    schedule: "Полная занятость",
    workHours: "11 (Вечерние или ночные смены)",
    workFormat: "на месте работодателя",
    salary: {
      startSalary: 80000,
      endSalary: 21000,
    },
    graffic: null,
    link: "https://tyumen.hh.ru/vacancy/117304866?hhtmFrom=vacancy_search_list",
  },
  {
    name: "Инженер-программист",
    payments: "два раза в месяц",
    experience: "3–6 лет",
    schedule: "Полная занятость",
    workHours: "8",
    workFormat: null,
    salary: {
      startSalary: 100000,
      endSalary: null,
    },
    graffic: "5/2",
    link: "https://tyumen.hh.ru/vacancy/117514427?hhtmFrom=vacancy_search_list",
  },
  {
    name: "Инженер-программист",
    payments: "два раза в месяц",
    experience: "1–3 года",
    schedule: "Полная занятость",
    workHours: "8",
    workFormat: null,
    salary: {
      startSalary: 100000,
      endSalary: null,
    },
    graffic: "5/2",
    link: "https://tyumen.hh.ru/vacancy/117514427?hhtmFrom=vacancy_search_list",
  },
  {
    name: "Наладчик станков с ЧПУ ",
    payments: "два раза в месяц",
    experience: "1–3 года",
    schedule: "Полная занятость",
    workHours: "11 (Вечерние или ночные смены)",
    workFormat: "Полная занятость",
    salary: {
      startSalary: 50000,
      endSalary: 150000,
    },
    graffic: null,
    link: "https://tyumen.hh.ru/vacancy/117304866?hhtmFrom=vacancy_search_list",
  },
];
